"""Create paired *_t1.tif and *_t2.tif files from a manifest CSV.

This utility reads the manifest generated by the preprocessing step and
creates a directory containing paired files named <tile_id>_t1.tif and
<tile_id>_t2.tif so the existing dataset implementation (which looks for
*_t1.tif / *_t2.tif) can load training data.

It copies (or hard-links when possible) the original tile GeoTIFFs into the
target folder. On Windows hard links are possible but require admin rights;
we'll fall back to copying.
"""
import csv
import os
import shutil
from pathlib import Path
from typing import Optional


def make_pair_folder(manifest_csv: str, out_dir: str, overwrite: bool = False) -> None:
    """Create paired t1/t2 tif files from a manifest CSV.

    Args:
        manifest_csv: path to manifest.csv produced by `manifest` command
        out_dir: directory to create paired files in
        overwrite: if True, existing files will be overwritten
    """
    manifest_csv = Path(manifest_csv)
    out_dir = Path(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    with manifest_csv.open('r', newline='') as fh:
        reader = csv.DictReader(fh)
        rows = list(reader)

    if not rows:
        raise RuntimeError(f"Manifest {manifest_csv} contains no rows")

    for r in rows:
        tile_id = r.get('tile_id') or r.get('id') or r.get('name')
        pre = Path(r['pre_tile'])
        post = Path(r['post_tile'])

        if tile_id is None:
            # fallback to filename stem
            tile_id = pre.stem

        t1_target = out_dir / f"{tile_id}_t1.tif"
        t2_target = out_dir / f"{tile_id}_t2.tif"

        for src, dst in ((pre, t1_target), (post, t2_target)):
            if dst.exists():
                if overwrite:
                    dst.unlink()
                else:
                    # skip existing
                    continue

            try:
                # try to create a hard link first (cheap)
                os.link(str(src), str(dst))
            except Exception:
                # fall back to copy
                shutil.copy2(str(src), str(dst))


if __name__ == '__main__':
    import argparse

    p = argparse.ArgumentParser(description='Create paired *_t1.tif and *_t2.tif from manifest')
    p.add_argument('manifest', help='Path to manifest.csv')
    p.add_argument('out_dir', help='Output directory for paired files')
    p.add_argument('--overwrite', action='store_true')
    args = p.parse_args()
    make_pair_folder(args.manifest, args.out_dir, overwrite=args.overwrite)
